ASCDEV_SYSTEM_COPYRIGHT :str = 'ASCDEV SYSTEM DEV ©Copyright'
INIT_DATA_BASE_FILE_NAME :str = "CoreData.mdb"
INIT_DIRECTORY_CORE :str = "core\\"
INIT_DIRECTORY_DATA :str = "data\\"
INIT_DIRECTORY_USERS :str = "users\\"
INIT_ICON_PATH :str = "icon"
INIT_ICON_NAME :str = "dprm_main.ico"

INIT_DIRECTORY_TENSORFLOW :str = "lm\\"
INIT_DIRECTORY_TENSORFLOW_MODEL :str = "model\\"
WIN_TENSORFLOW_TITLE_WINDOWS :str = 'TENSORFLOW Application Modeling'
INIT_IMAGE_TENSORFLOW_PATH :str = "image\\"
INIT_IMAGE_TENSORFLOW_NAME :str = "INIT_DOG_4_LM.png"


INIT_DEFAULT_SERV_IP_PORT :str  = "0.0.0.0:8080"

GUI_COLOR_BASE_SCREEN_BACK_COLOR :str = 'gray40'
GUI_COLOR_BASE_SCREEN_FORE_COLOR :str = 'black'

GUI_COLOR_BASE_FRAME_BACK_COLOR :str = 'gray23'
GUI_COLOR_BASE_FRAME_FORE_COLOR :str = 'black'

WIN_ADM_TITLE_WINDOWS :str = 'DPRM Administration and Users Management'
WIN_ADM_SERVER_FRAME_ID :int = 0 
WIN_ADM_USERS_FRAME_ID :int = 1
WIN_ADM_STATISTICS_FRAME_ID :int = 2

WEB_TAG_REQUEST_INDEX :str = "INDEX"
WEB_TAG_REQUEST_SIGNIN :str = "SIGNIN"
WEB_TAG_REQUEST_LOGIN :str = "LOGIN"
WEB_TAG_REQUEST_SIGNIN_SUBMIT :str = "SIGNIN_SUBMIT"
WEB_TAG_REQUEST_LOGIN_SUBMIT :str = "LOGIN_SUBMIT"

USR_DEFAULT_MAIN_DATA_BASE_NAME = "UserData.mdb"

WEB_TAG_ROUTAGE_LOGOUT :str = "LOG_OUT"
WEB_TAG_ROUTAGE_SETTINGS :str = "SETTINGS"
WEB_TAG_ROUTAGE_HOME :str = "HOME"
WEB_TAG_ROUTAGE_SAVE_SETTING :str = "SAVE_SETTING"
WEB_TAG_ROUTAGE_CLOSE_ACCOUNT :str = "CLOSE_ACCOUNT"
WEB_TAG_ROUTAGE_SAVE_PASSWORD :str = "SAVE_PASSWORD"
WEB_TAG_ROUTAGE_ADD_WORKSPACE :str = "ADD_WORKSPACE"
WEB_TAG_ROUTAGE_DEL_WORKSPACE :str = "DEL_WORKSPACE"
WEB_TAG_ROUTAGE_SELECT_WORKSPACE :str = "SELECT_WORKSPACE"

WEB_TAG_ROUTAGE_ADD_REQUEST :str = "ADD_REQUEST"
WEB_TAG_ROUTAGE_DELETE_REQUEST :str = "DELETE_REQUEST"
WEB_TAG_ROUTAGE_EDIT_REQUEST :str = "EDIT_REQUEST"
WEB_TAG_ROUTAGE_EXECUTE_REQUEST :str = "EXECUTE_REQUEST"
WEB_TAG_ROUTAGE_EXECUTE_ALL_REQUEST :str = "EXECUTE_ALL_REQUEST"

WEB_TAG_ROUTAGE_SCHEDULER :str = "SCHEDULER"
WEB_TAG_ROUTAGE_SAVE_SCHEDULER :str = "SAVE_SCHEDULER"
WEB_TAG_ROUTAGE_ACQUISITION_VALIDATION :str = "ACQUISITION_VALIDATION"
WEB_TAG_ROUTAGE_TRANSFORMATION_VALIDATION :str = "TRANSFORMATION_VALIDATION"
WEB_TAG_ROUTAGE_EXPLOITATION_VALIDATION :str = "EXPLOITATION_VALIDATION"

WEB_TAG_ROUTAGE_HEADER_ACQUISITION :str = "HEADER_ACQUISITION"
WEB_TAG_ROUTAGE_HEADER_TRANSFORMATION :str = "HEADER_TRANSFORMATION"
WEB_TAG_ROUTAGE_HEADER_EXPLOITATION :str = "HEADER_EXPLOITATION"

WORKSPACE_DEFAULT_DATA_BASE_NAME = "WorkSpace.mdb"








