
DEFAULT_DATA_SYS_ADMIN :dict = {"admin_password":"5ce41ada64f1e8ffb0acfaafa622b141438f3a5777785e7f0b830fb73e40d3d6", #Admin1234!
                                "admin_email":"adm@email.com", 
                                "company_name":"", 
                                "company_address":"", 
                                "company_contact":"", 
                                "server_ip_port":"0.0.0.0:8080", 
                                "smtp_server_ip_port":"", 
                                "smtp_user":"", 
                                "smtp_password":"", 
                                "smtp_from_email":"", 
                                "max_users_allowed":"100000", 
                                "google_public_storage_path":"",
                                "backup_path_directory":"",
                                "backup_time_cycle":"0",
                                "backup_last_time":"",
                                "python_path":"", 
                                "web_server_path":"", 
                                "is_redirect_server":"FALSE", 
                                "use_proxy_balancing":"FALSE", 
                                "is_backup_activate":"FALSE", 
                                "first_server_start_date":"", 
                                "last_backup_date":"",
                                "last_server_start_date":""}

DEFAULT_DATA_SYS_BACKUP_DEF :list[tuple] = [(0, "D6,08:00", "Once Per Week Saturday At 08:00"),
                                            (1, "D7,08:00", "Once Per Week Sunday At 08:00"),
                                            (2, "D5,08:00", "Once Per Week friday At 08:00"),
                                            (3, "D6,22:00", "Once Per Week Saturday At 22:00"),
                                            (4, "D7,22:00", "Once Per Week Sunday At 22:00"),
                                            (5, "D5,22:00", "Once Per Week friday At 22:00"),
                                            (6, "D0,08:00", "Once Per Day All Days At 08:00"),
                                            (7, "D0,22:00", "Once Per Day All Days At 22:00")]

DEFAULT_DATA_USER_COUNTRY_DEF :list[tuple] = [("AX","Åland Islands"),
                                              ("AL","Albania"),
                                              ("DZ","Algeria"),
                                              ("AS","American Samoa"),
                                              ("AD","Andorra"),
                                              ("AO","Angola"),
                                              ("AI","Anguilla"),
                                              ("AQ","Antarctica"),
                                              ("AG","Antigua and Barbuda"),
                                              ("AR","Argentina"),
                                              ("AM","Armenia"),
                                              ("AW","Aruba"),
                                              ("AU","Australia"),
                                              ("AT","Austria"),
                                              ("AZ","Azerbaijan"),
                                              ("BS","Bahamas"),
                                              ("BH","Bahrain"),
                                              ("BD","Bangladesh"),
                                              ("BB","Barbados"),
                                              ("BY","Belarus"),
                                              ("BE","Belgium"),
                                              ("BZ","Belize"),
                                              ("BJ","Benin"),
                                              ("BM","Bermuda"),
                                              ("BT","Bhutan"),
                                              ("BO","Bolivia (Plurinational State of)"),
                                              ("BA","Bosnia and Herzegovina"),
                                              ("BW","Botswana"),
                                              ("BV","Bouvet Island"),
                                              ("BR","Brazil"),
                                              ("IO","British Indian Ocean Territory"),
                                              ("BN","Brunei Darussalam"),
                                              ("BG","Bulgaria"),
                                              ("BF","Burkina Faso"),
                                              ("BI","Burundi"),
                                              ("CV","Cabo Verde"),
                                              ("KH","Cambodia"),
                                              ("CM","Cameroon"),
                                              ("CA","Canada"),
                                              ("BQ","Caribbean Netherlands"),
                                              ("KY","Cayman Islands"),
                                              ("CF","Central African Republic"),
                                              ("TD","Chad"),
                                              ("CL","Chile"),
                                              ("CN","China"),
                                              ("CX","Christmas Island"),
                                              ("CC","Cocos (Keeling) Islands"),
                                              ("CO","Colombia"),
                                              ("KM","Comoros"),
                                              ("CG","Congo"),
                                              ("CD","Congo, Democratic Republic of the"),
                                              ("CK","Cook Islands"),
                                              ("CR","Costa Rica"),
                                              ("HR","Croatia"),
                                              ("CU","Cuba"),
                                              ("CW","Curaçao"),
                                              ("CY","Cyprus"),
                                              ("CZ","Czech Republic"),
                                              ("CI","Côte d''Ivoire"),
                                              ("DK","Denmark"),
                                              ("DJ","Djibouti"),
                                              ("DM","Dominica"),
                                              ("DO","Dominican Republic"),
                                              ("EC","Ecuador"),
                                              ("EG","Egypt"),
                                              ("SV","El Salvador"),
                                              ("GQ","Equatorial Guinea"),
                                              ("ER","Eritrea"),
                                              ("EE","Estonia"),
                                              ("SZ","Eswatini (Swaziland)"),
                                              ("ET","Ethiopia"),
                                              ("FK","Falkland Islands (Malvinas)"),
                                              ("FO","Faroe Islands"),
                                              ("FJ","Fiji"),
                                              ("FI","Finland"),
                                              ("FR","France"),
                                              ("GF","French Guiana"),
                                              ("PF","French Polynesia"),
                                              ("TF","French Southern Territories"),
                                              ("GA","Gabon"),
                                              ("GM","Gambia"),
                                              ("GE","Georgia"),
                                              ("DE","Germany"),
                                              ("GH","Ghana"),
                                              ("GI","Gibraltar"),
                                              ("GR","Greece"),
                                              ("GL","Greenland"),
                                              ("GD","Grenada"),
                                              ("GP","Guadeloupe"),
                                              ("GU","Guam"),
                                              ("GT","Guatemala"),
                                              ("GG","Guernsey"),
                                              ("GN","Guinea"),
                                              ("GW","Guinea-Bissau"),
                                              ("GY","Guyana"),
                                              ("HT","Haiti"),
                                              ("HM","Heard Island and Mcdonald Islands"),
                                              ("HN","Honduras"),
                                              ("HK","Hong Kong"),
                                              ("HU","Hungary"),
                                              ("IS","Iceland"),
                                              ("IN","India"),
                                              ("ID","Indonesia"),
                                              ("IR","Iran"),
                                              ("IQ","Iraq"),
                                              ("IE","Ireland"),
                                              ("IM","Isle of Man"),
                                              ("IL","Israel"),
                                              ("IT","Italy"),
                                              ("JM","Jamaica"),
                                              ("JP","Japan"),
                                              ("JE","Jersey"),
                                              ("JO","Jordan"),
                                              ("KZ","Kazakhstan"),
                                              ("KE","Kenya"),
                                              ("KI","Kiribati"),
                                              ("KP","Korea, North"),
                                              ("KR","Korea, South"),
                                              ("XK","Kosovo"),
                                              ("KW","Kuwait"),
                                              ("KG","Kyrgyzstan"),
                                              ("LA","Lao People''s Democratic Republic"),
                                              ("LV","Latvia"),
                                              ("LB","Lebanon"),
                                              ("LS","Lesotho"),
                                              ("LR","Liberia"),
                                              ("LY","Libya"),
                                              ("LI","Liechtenstein"),
                                              ("LT","Lithuania"),
                                              ("LU","Luxembourg"),
                                              ("MO","Macao"),
                                              ("MK","Macedonia North"),
                                              ("MG","Madagascar"),
                                              ("MW","Malawi"),
                                              ("MY","Malaysia"),
                                              ("MV","Maldives"),
                                              ("ML","Mali"),
                                              ("MT","Malta"),
                                              ("MH","Marshall Islands"),
                                              ("MQ","Martinique"),
                                              ("MR","Mauritania"),
                                              ("MU","Mauritius"),
                                              ("YT","Mayotte"),
                                              ("MX","Mexico"),
                                              ("FM","Micronesia"),
                                              ("MD","Moldova"),
                                              ("MC","Monaco"),
                                              ("MN","Mongolia"),
                                              ("ME","Montenegro"),
                                              ("MS","Montserrat"),
                                              ("MA","Morocco"),
                                              ("MZ","Mozambique"),
                                              ("MM","Myanmar (Burma)"),
                                              ("NA","Namibia"),
                                              ("NR","Nauru"),
                                              ("NP","Nepal"),
                                              ("NL","Netherlands"),
                                              ("AN","Netherlands Antilles"),
                                              ("NC","New Caledonia"),
                                              ("NZ","New Zealand"),
                                              ("NI","Nicaragua"),
                                              ("NE","Niger"),
                                              ("NG","Nigeria"),
                                              ("NU","Niue"),
                                              ("NF","Norfolk Island"),
                                              ("MP","Northern Mariana Islands"),
                                              ("NO","Norway"),
                                              ("OM","Oman"),
                                              ("PK","Pakistan"),
                                              ("PW","Palau"),
                                              ("PS","Palestine"),
                                              ("PA","Panama"),
                                              ("PG","Papua New Guinea"),
                                              ("PY","Paraguay"),
                                              ("PE","Peru"),
                                              ("PH","Philippines"),
                                              ("PN","Pitcairn Islands"),
                                              ("PL","Poland"),
                                              ("PT","Portugal"),
                                              ("PR","Puerto Rico"),
                                              ("QA","Qatar"),
                                              ("RE","Reunion"),
                                              ("RO","Romania"),
                                              ("RU","Russian Federation"),
                                              ("RW","Rwanda"),
                                              ("BL","Saint Barthelemy"),
                                              ("SH","Saint Helena"),
                                              ("KN","Saint Kitts and Nevis"),
                                              ("LC","Saint Lucia"),
                                              ("MF","Saint Martin"),
                                              ("PM","Saint Pierre and Miquelon"),
                                              ("VC","Saint Vincent and the Grenadines"),
                                              ("WS","Samoa"),
                                              ("SM","San Marino"),
                                              ("ST","Sao Tome and Principe"),
                                              ("SA","Saudi Arabia"),
                                              ("SN","Senegal"),
                                              ("RS","Serbia"),
                                              ("CS","Serbia and Montenegro"),
                                              ("SC","Seychelles"),
                                              ("SL","Sierra Leone"),
                                              ("SG","Singapore"),
                                              ("SX","Sint Maarten"),
                                              ("SK","Slovakia"),
                                              ("SI","Slovenia"),
                                              ("SB","Solomon Islands"),
                                              ("SO","Somalia"),
                                              ("ZA","South Africa"),
                                              ("GS","South Georgia and the South Sandwich Islands"),
                                              ("SS","South Sudan"),
                                              ("ES","Spain"),
                                              ("LK","Sri Lanka"),
                                              ("SD","Sudan"),
                                              ("SR","Suriname"),
                                              ("SJ","Svalbard and Jan Mayen"),
                                              ("SE","Sweden"),
                                              ("CH","Switzerland"),
                                              ("SY","Syria"),
                                              ("TW","Taiwan"),
                                              ("TJ","Tajikistan"),
                                              ("TZ","Tanzania"),
                                              ("TH","Thailand"),
                                              ("TL","Timor-Leste"),
                                              ("TG","Togo"),
                                              ("TK","Tokelau"),
                                              ("TO","Tonga"),
                                              ("TT","Trinidad and Tobago"),
                                              ("TN","Tunisia"),
                                              ("TR","Turkey (Türkiye)"),
                                              ("TM","Turkmenistan"),
                                              ("TC","Turks and Caicos Islands"),
                                              ("TV","Tuvalu"),
                                              ("UM","U.S. Outlying Islands"),
                                              ("UG","Uganda"),
                                              ("UA","Ukraine"),
                                              ("AE","United Arab Emirates"),
                                              ("GB","United Kingdom"),
                                              ("US","United States"),
                                              ("UY","Uruguay"),
                                              ("UZ","Uzbekistan"),
                                              ("VU","Vanuatu"),
                                              ("VA","Vatican City Holy See"),
                                              ("VE","Venezuela"),
                                              ("VN","Vietnam"),
                                              ("VG","Virgin Islands, British"),
                                              ("VI","Virgin Islands, U.S"),
                                              ("WF","Wallis and Futuna"),
                                              ("EH","Western Sahara"),
                                              ("YE","Yemen"),
                                              ("ZM","Zambia"),
                                              ("ZW","Zimbabwe"),]
